runtime: php
env: flex

runtime_config:
  document_root: public

  skip_files:
    -.env
  env_variables:
#    APP_LOG:
#    APP_DEBUG: true
#    APP_KEY: base64:0Ydrq6+qdyE7mZV1jYuintLwgQ0n30Tl12qYurmFMn8=
#    STORAGE_DIR: /tmp
#    CACHE_DRIVER: file
#    DB_CONNECTION: mysql
#    DB_HOST: localhost
#    DB_PORT: 3306
#    DB_DATABASE: usersapp
#    DB_PASSWORD: usersapp
#    DB_SOCKET: usersapp

beta_settings:
  cloud_sql_instances:
